# Generated by Django 4.2.11 on 2024-05-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
    ]
