# Generated by Django 4.2.11 on 2024-05-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('license_plate', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('generation', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('fuel', models.CharField(max_length=20)),
                ('fuel_consumption', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
